# Generated by Django 2.2.28 on 2024-11-24 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_auto_20241124_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='carte',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
