# Generated by Django 2.2.28 on 2024-11-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_carte_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carte',
            name='Hp',
        ),
        migrations.RemoveField(
            model_name='carte',
            name='Type',
        ),
        migrations.RemoveField(
            model_name='carte',
            name='author',
        ),
        migrations.RemoveField(
            model_name='carte',
            name='created_date',
        ),
        migrations.AddField(
            model_name='carte',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carte',
            name='text',
            field=models.TextField(default='Texte par défaut'),
        ),
        migrations.AddField(
            model_name='carte',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
