# Generated by Django 2.2.28 on 2024-11-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0006_carte_pv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carte',
            name='Pv',
            field=models.IntegerField(default=0),
        ),
    ]
